### ISSUE TITLE
TZ handling

### ISSUE THREAD

**Issue by rfuxx** [stv0g/calcelestial#13]
I had a problem that calcelestial did not pick up my default system timezone, and with the -z parameter I could not specify "long" timezones like "Europe/Berlin" but only "short" ones like "CET".
The system where this has appared is a raspi with Raspian; the TZ variable is not set, but looks like the system picks up the the local time zone via /etc/localtime .

The [attached change](https://github.com/stv0g/calcelestial/files/605634/calcelectial-tzhandling.diff.txt) worked for me to have my problem fixed, and it is now both picking up the correct system timezone as default, and also a "long" other timezone (such as e.g. "Asia/Singapore") can be specified on the -z parameter.

[calcelectial-tzhandling.diff.txt](https://github.com/stv0g/calcelestial/files/605634/calcelectial-tzhandling.diff.txt)

**Comment by stv0g** [comment]
Thanks @rfuxx I applied your patch.
