### ISSUE TITLE
default format not compatible with at

### ISSUE THREAD

**Issue by justinotherguy** [stv0g/calcelestial#18]
Moin,

starting calcestial as shown in your blog post (https://www.noteblok.net/2013/05/05/calcelestial/) I get this:

```
justin@robbi:/etc/cron.d# calcelestial -p sun -q Frankfurt -m set
time: 2017-02-23 17:55:59 (CET) az: 256.081 (SWW) alt: 358.759
```

Feeding this into at results in an unhappy at command:
```
justin@robbi:/etc/cron.d# at $(calcelestial -p sun -q Frankfurt -m set)
syntax error. Last token seen: t
Garbled time
```

Adding an explicit output format this can be fixed:
```
justin@robbi:/etc/cron.d# echo "bla" | at $(/usr/local/bin/calcelestial -p sun -q Frankfurt -m set -f "%H%M %Y-%m-%d")
warning: commands will be executed using /bin/sh
job 14 at Thu Feb 23 17:55:00 2017
```

Is that desired behaviour? Then you might want to update your  blog post.

Regards, J.

**Comment by justinotherguy** [comment]
to include the working statement above in a cron job the percent character ("%") needs to be quoted, e.g.:
0 0 * * * echo '/usr/bin/curl -s "<some url>"' | at $(/usr/local/bin/calcelestial -p sun -q Frankfurt -m rise -n -f "\%H\%M")
It does the job then. Still, not pretty.

**Comment by stv0g** [comment]
This is working for me:

```
$ echo bla | at $(calcelestial -p sun -m rise -q 'La Paz' -n)
job 2 at Sat Mar  4 06:32:00 2017
```

**Comment by justinotherguy** [comment]
Confirmed - works for me now, too ;-)
It was not working with commit 1982c6be694ff76e26182bf032d44b00b024346e and the ones before.
Thanks!
