### ISSUE TITLE
geht nicht

### ISSUE THREAD

**Issue by bobybobybob** [stv0g/calcelestial#4]
nach .configure erscheint

```
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
./configure: line 3494: syntax error near unexpected token `DEPS_GEONAMES,'
./configure: line 3494: `    PKG_CHECK_MODULES(DEPS_GEONAMES, libcurl >= 7.21, json-c >= 0.11)'
````

Ich komme da nicht weiter...  ich verwende Armbian_5.20_Bananapim2_Debian_jessie_4.7.3
Habe von linux keine Ahnung... irgendwo im internet so ein Installationsscript gefunden.

**Comment by bobybobybob** [comment]
Es wäre auch toll wenn die Hilfedateien in Deutsch wären statt in einer Fremdsprache.

**Comment by stv0g** [comment]
This is not a bug. Please see https://coffeecode.net/archives/208-PKG_CHECK_MODULES-syntax-error-near-unexpected-token-DEPS,.html

(This was the first result which showed up on google...)

> Es wäre auch toll wenn die Hilfedateien in Deutsch wären statt in einer Fremdsprache.

Sorry, I provide documentation to all of my projects only in English.

As this is an open source project, please feel free to contribute a translated version.

**Comment by bobybobybob** [comment]
Ich habe das Programm mit einer anderen Linux Version zum laufen gebracht. War nicht einfach...

**Comment by bobybobybob** [comment]
Achja bei der Gelegenheit noch ein Wort
Danke für das Super Programm. Es sollte Bestandteil eines jeden Linux sein.
